### ISSUE TITLE
Create `terms-of-use.md` file with correct contents

### ISSUE THREAD

**Issue by Samyoul** [status-im/status-software-legal-documents#2]
- [x] In the root dir create a file named `terms-of-use.md`.
- [x] Add the contents from this document [Status Software Terms of Use](https://docs.google.com/document/d/1JIhxYhB5aVCzq6acD7TSpvcVg1p37C9H/edit)
- [x] Ensure that when you open the PR that the `Legal` team is a mandatory reviewer
- [x] Ensure that merging is not possible without the `Legal` team's review
- [x] Merge once `Legal` have approved the PR.

Sorry that the steps in this PR seem a bit specific, I just don't know if I have correctly set the permissions and I can't check without removing myself as an admin, which block me from tweaking the permissions if they are configured wrong 😄 .

**Comment by flexsurfer** [comment]
@Samyoul seems like merge is possible already
<img width="494" alt="image" src="https://github.com/user-attachments/assets/a957bc4c-493f-499b-b79a-a903f5b20117">

**Comment by Samyoul** [comment]
resolved with #4
